FROM amazoncorretto:11-alpine-jdk
MAINTAINER Walter Halm      
copy target/SpringBoot-0.0.1-SNAPSHOT.jar portfoliowalterhalm-app.jar   
entrypoint["java","-jar","/portfolioWalterHalm-app.jar"]                               
