FROM amazoncorretto:11-alpine-jdk //version java
MAINTAINER Walter Halm      //dueño
copy target/SpringBoot-0.0.1-SNAPSHOT.jar portfolioWalterHalm-app.jar   //empaquetado github
entrypoint["java","-jar","/portfolioWalterHalm-app.jar"]                               //instrucciones
